### ISSUE TITLE
Error while open 打包设置管理器(Package Settings Manager) on Unity 2017.3.0f3

### ISSUE THREAD

**Issue by takaaptech** [GaoKaiHaHa/MyUnityFrameWork#12]
Hi!
After update to Unity 2017.3 I have error when open 打包设置管理器(Package Settings Manager) window:
(Unity 2017.2 works well) Thank so much!

IndexOutOfRangeException: Array index is out of range.
UnityEditor.MaskFieldGUI.GetMenuOptions (Int32 mask, System.String[] flagNames, System.Int32[] flagValues, System.String& buttonText, System.String[]& optionNames, System.Int32[]& optionMaskValues, System.Int32[]& selectedOptions) (at /Users/builduser/buildslave/unity/build/Editor/Mono/GUI/MaskFieldGUI.cs:157)
UnityEditor.MaskFieldGUI.DoMaskField (Rect position, Int32 controlID, Int32 mask, System.String[] flagNames, System.Int32[] flagValues, UnityEngine.GUIStyle style, System.Int32& changedFlags, System.Boolean& changedToValue) (at /Users/builduser/buildslave/unity/build/Editor/Mono/GUI/MaskFieldGUI.cs:114)
UnityEditor.MaskFieldGUI.DoMaskField (Rect position, Int32 controlID, Int32 mask, System.String[] flagNames, UnityEngine.GUIStyle style, System.Int32& changedFlags, System.Boolean& changedToValue) (at /Users/builduser/buildslave/unity/build/Editor/Mono/GUI/MaskFieldGUI.cs:100)
UnityEditor.MaskFieldGUI.DoMaskField (Rect position, Int32 controlID, Int32 mask, System.String[] flagNames, UnityEngine.GUIStyle style) (at /Users/builduser/buildslave/unity/build/Editor/Mono/GUI/MaskFieldGUI.cs:84)
UnityEditor.EditorGUI.MaskFieldInternal (Rect position, Int32 mask, System.String[] displayedOptions, UnityEngine.GUIStyle style) (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorGUI.cs:3119)
UnityEditor.EditorGUI.MaskField (Rect position, Int32 mask, System.String[] displayedOptions, UnityEngine.GUIStyle style) (at /Users/builduser/buildslave/unity/build/artifacts/generated/common/editor/EditorGUIBindings.gen.cs:782)
UnityEditor.EditorGUILayout.MaskField (Int32 mask, System.String[] displayedOptions, UnityEngine.GUILayoutOption[] options) (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorGUI.cs:7196)
BundleConfigEditorWindow.OnGUI () (at Assets/Script/Core/Editor/Package/PackageConfigEditorWindow.cs:81)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:295)
UnityEditor.HostView.Invoke (System.String methodName) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:288)
UnityEditor.HostView.InvokeOnGUI (Rect onGUIPosition) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:255)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by takaaptech** [comment]
Hi!
Length = 0 and RelyMaskFilter = -1

**Comment by GaoKaiHaHa** [comment]
bug has been fixed :)

**Comment by takaaptech** [comment]
Confirmed! Thank so much @GaoKaiHaHa !!!!
