### ISSUE TITLE
Please update more wiki

### ISSUE THREAD

**Issue by takaaptech** [GaoKaiHaHa/MyUnityFrameWork#13]
Hi @GaoKaiHaHa !
Please update quick note and simple about
Beginner's guide
Lua
Game Object Manager
Audio Manager
Animation system
...

Thank so much!

**Comment by GaoKaiHaHa** [comment]
[Beginner's guide](https://github.com/GaoKaiHaHa/MyUnityFrameWork/wiki/Beginner's-guide)

**Comment by takaaptech** [comment]
Hi!
Thank so much! @GaoKaiHaHa !!!
keep up the good work!

**Comment by takaaptech** [comment]
@GaoKaiHaHa Please add more note! Thank so much !!!!

**Comment by GaoKaiHaHa** [comment]
sorry,A little busy lately  :)

**Comment by GaoKaiHaHa** [comment]
@takaaptech 
[Lua](https://github.com/GaoKaiHaHa/MyUnityFrameWork/wiki/LUA-en)
[Game Object Manager](https://github.com/GaoKaiHaHa/MyUnityFrameWork/wiki/GameObjectManager)
[Audio Manager](https://github.com/GaoKaiHaHa/MyUnityFrameWork/wiki/AudioManager)

**Comment by takaaptech** [comment]
@GaoKaiHaHa Thank so much and happy new year!

**Comment by takaaptech** [comment]
I am waiting for:

Developer Console
Animation system
Input Manager
SDK Manager
Other

Thank so much @GaoKaiHaHa !

**Comment by takaaptech** [comment]
@GaoKaiHaHa Update, please! Want to learn from you a lot! Thank so much!

**Comment by GaoKaiHaHa** [comment]
@takaaptech hi
[Developer Console](https://github.com/GaoKaiHaHa/MyUnityFrameWork/wiki/Developer-Console)  
[Animation system](https://github.com/GaoKaiHaHa/MyUnityFrameWork/wiki/Animation-system)

Input Manager related to playback mode, it will not be introduced separately
SDK Manager has not finished yet

**Comment by takaaptech** [comment]
@GaoKaiHaHa ! Thank so much for your support!

**Comment by GaoKaiHaHa** [comment]
U R welcome ：）
