### ISSUE TITLE
Question about what is difference between Data, Configuration,  Persistent data

### ISSUE THREAD

**Issue by takaaptech** [GaoKaiHaHa/MyUnityFrameWork#14]
Hi!
After reading wiki and viewing example code, i still have some confuse about Data, Configuration and Persistent data.
- Persistent data: is this like unity playerprefs, but we use json to store persistent data?
- Data: can we import data from excel file?
- What kind of data should we store in Configuration, I still can not understand what configuration for?

Thank so much!

**Comment by GaoKaiHaHa** [comment]
1. Functions are basically similar, but we can use the persistence editor to edit all the persistence data.
2.Yes, but we need a converter
3.The advantage of the configuration is that you can put the same module's settings together without having to keep the same formatting as the data. For example, you can put whether to turn on the hot and hot update addresses in one configuration.

**Comment by takaaptech** [comment]
Excellence! I can understand it now! Thank so much!
