### ISSUE TITLE
How to transfer (communicate, pass) data between UIWindowBase

### ISSUE THREAD

**Issue by takaaptech** [GaoKaiHaHa/MyUnityFrameWork#16]
Hi again!
I want to understand what is common and best way to pass data between UIWindowBase (window)
For example:
 - From window1 we pass some data each time window2 open (by press button on window 1) will get data and draw some UI base on that data.
 - And then when we in window2, we modify some data and close window2, put some data back to window1, window1 will collect data and then update some UI.

Thank so much!

**Comment by GaoKaiHaHa** [comment]
The usual practice is that the UI does not save the data, the data stored in the model layer (MVC), when the data is updated, distribute this event, the other UI listened to this event, reread the data to update itself,

the event can be distributed GlobalEvent this class, this is another wiki :)

**Comment by GaoKaiHaHa** [comment]
The usual practice is that the UI does not save the data, the data stored in the model layer (MVC), when the data is updated, distribute this event, the other UI listened to this event, reread the data to update itself,

the event can be distributed GlobalEvent this class, this is another wiki :)

**Comment by takaaptech** [comment]
OK thank for clearing that!
How about model layer class, is it a normal class or extend from some class in the framework?

**Comment by GaoKaiHaHa** [comment]
Is a normal class that dispatches the corresponding event when it is modified.

**Comment by takaaptech** [comment]
So i will wait for GlobalEvent wiki page! Thank @GaoKaiHaHa !
