### ISSUE TITLE
Best practice for using IApplicationStatus (Game States)

### ISSUE THREAD

**Issue by takaaptech** [GaoKaiHaHa/MyUnityFrameWork#17]
Hi!
In the demo, I see some class extend from IApplicationStatus. How to use it and what does it for?
What is it role in MVC model or it does not belong to MVC model?
Is every UIWindow need an IApplicationStatus?
Thank in advance!

**Comment by GaoKaiHaHa** [comment]
@takaaptech hi!
When you create a class that inherits from IApplicationStatus, it can be selected as the first Status in ApplicationManager. In Developing Mode, the EnterStatusTestData method is executed and you can use it to initialize the test data, which you can think of as a state machine , You can create a UI in this state, when this state exits, the UI created by this Status will be automatically destroyed, and you can write logic inside to make it play the role of Controller.

**Comment by takaaptech** [comment]
@GaoKaiHaHa Thanks! Your framework is awesome!
By the way, when thinking IApplicationStatus as State in the state machine, do the framework supports FSM, so we can simply fire an Event for changing State. And that way we can predefine flow of many states and transition between them from start.
Thank so much!

**Comment by GaoKaiHaHa** [comment]
@takaaptech hi
We can register the event listener in OnEnterStatus so that when the event is dispatched we can toggle the state : )

**Comment by takaaptech** [comment]
I got it! No need to complicate things more! Simply is the best!
Thank so much!

**Comment by GaoKaiHaHa** [comment]
： ）
