### ISSUE TITLE
Update the wiki and Global Event?

### ISSUE THREAD

**Issue by takaaptech** [GaoKaiHaHa/MyUnityFrameWork#18]
Hi @GaoKaiHaHa !
Please update the wiki and Global Event!
Many thank for this!

**Comment by GaoKaiHaHa** [comment]
@takaaptech hi !
[Event System](https://github.com/GaoKaiHaHa/MyUnityFrameWork/wiki/Event-System)

**Comment by takaaptech** [comment]
@GaoKaiHaHa ! Just read it! Very powerful API!
Just want to ask if I have only one-time 
GlobalEvent.AddEvent ("GameStart", ReceviceGameStart);
So that will this function
 GlobalEvent.RemoveEvent ("GameStart", ReceviceGameStart);
equals to
GlobalEvent.RemoveEvent ("GameStart"); 
Thank so much!

**Comment by GaoKaiHaHa** [comment]
If you can guarantee that you only used `AddEvent (string eventKey, EventHandle handle, bool isUseOnce = false)` once, then the two methods are the same, but I do not recommend doing this because it will increase the difficulty of reading the code and increase the error may

**Comment by takaaptech** [comment]
Thank so much @GaoKaiHaHa I will try to practice your comment!
