### ISSUE TITLE
Please add Networked system to wiki

### ISSUE THREAD

**Issue by takaaptech** [GaoKaiHaHa/MyUnityFrameWork#19]
Hi!
I see in readme we have "Networked system" session!
Please add some info to wiki
What is server we use with our client?
It is awesome if you have a simple demo about server and client!
Thank so much!

**Comment by takaaptech** [comment]
Hi @GaoKaiHaHa Any update?

**Comment by GaoKaiHaHa** [comment]
hi @takaaptech 
[Network](https://github.com/GaoKaiHaHa/MyUnityFrameWork/wiki/Network)
by the way 
[Language Manager](https://github.com/GaoKaiHaHa/MyUnityFrameWork/wiki/Language-manager)

**Comment by takaaptech** [comment]
Hi @GaoKaiHaHa ! Super! Thank so much!
And Happy Lunar New Year 2018! wish you all the best!
