### ISSUE TITLE
关于5.X

### ISSUE THREAD

**Issue by dingxiaowei** [GaoKaiHaHa/MyUnityFrameWork#2]
5.X的版本 有报错

**Comment by GaoKaiHaHa** [comment]
是场景的版本太高吗？还是有编译错误？我重新提交了一个5.3版本的主场景

**Comment by GaoKaiHaHa** [comment]
修复warp问题，可以先删除Script/LuaGenerate/这个文件夹，待编译过后，在Window->Lua设置编辑器中，选择Lua项目初始化，或者点击重新生成LuaWarp脚本。

**Comment by yh1094632455** [comment]
Lua Start Execption LuaInterface.LuaException: [string "LuaUnityDefine"]:1: attempt to index global 'UnityEngine' (a nil value)

这个是为啥，warp文件有导出，unity 版本5.3.4

**Comment by GaoKaiHaHa** [comment]
请把LuaManager.cs文件中 第30行 //LuaBinder.Bind(s_state);的注释放开
