### ISSUE TITLE
Please Update "Hot update" session in Wiki

### ISSUE THREAD

**Issue by takaaptech** [GaoKaiHaHa/MyUnityFrameWork#20]
Hi @GaoKaiHaHa !
Inside "Resource Management" there is "Hot update" feature that is missing.
Please update or create a new wiki page, thank you so much!

**Comment by GaoKaiHaHa** [comment]
HI!@takaaptech 
[Hot Update](https://github.com/GaoKaiHaHa/MyUnityFrameWork/wiki/Resource-Management)

**Comment by takaaptech** [comment]
Thank so much for this!
