### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by karsion** [GaoKaiHaHa/MyUnityFrameWork#21]
Timer Update 中一次性RemoveAll完结的Timer，避免多次Array.Copy

**Comment by GaoKaiHaHa** [comment]
感谢指教，已优化。

**Comment by karsion** [comment]
不客气，因为我看到一个Fork还是停留在Remove(item)的代码，比RemoveAt(int)还多了一次遍历。
当前版本还建议弄一个临时变量bool isSomeTimerDone，当任意if (m_timers[i].m_isDone) 为true的时候，标志一下isSomeTimerDone = true，遍历完后判断isSomeTimerDone才执行RemoveAll，避免每次Update都遍历数组。（反编译mscorlib.dll看一下List<T>源码）

**Comment by GaoKaiHaHa** [comment]
非常感谢提醒
