### ISSUE TITLE
How to organize GameObject (Player, Enemy Sprite) and GameWindow (Canvas, Panel, Button ..)

### ISSUE THREAD

**Issue by takaaptech** [GaoKaiHaHa/MyUnityFrameWork#22]
Hi @GaoKaiHaHa!
I am getting stuck in organize GUI (UIWindow) and Unity Game Object (Transform with Sprite Component,..) 
I am using one Unity Scene for all Windows (MainMenu, Setting, MainGame, PauseGame ...),
so should I put the game object into MainGame GUI Prefab or separate it at new Game Object on Hierarchy and enable it when we Open the MainGame Window?
What is the best practice of organizing in-game object if we using One Unity Scene for the game
Thank so much!

**Comment by GaoKaiHaHa** [comment]
hi !@takaaptech 
My suggestion is that the UI is not responsible for the creation of game objects. Instead, it is determined by more upper game logic to create game objects. In this framework, I suggest you to create game objects and handle game logic in ApplicationStatus.

**Comment by takaaptech** [comment]
Hi @GaoKaiHaHa!
Thank so much I can understand now.
Would I Create Prefab of the game object and then in ApplicationStatus we can Instantiate it by ResourceManager.Load 
or just create the game object to the Editor Hierarchy and then in the ApplicationStatus we enable it?

**Comment by GaoKaiHaHa** [comment]
Hi @takaaptech 
My suggestion is the former, don't put too much stuff in the main scene, keep the main scene simple

**Comment by takaaptech** [comment]
Thank so much for the incredibly fast support!
