### ISSUE TITLE
Add BlackPanel Translucent Background when show Popup WindowUI

### ISSUE THREAD

**Issue by takaaptech** [GaoKaiHaHa/MyUnityFrameWork#23]
Hi @GaoKaiHaHa 
We should add into framework feature that when show popup window that not fullscreen, then a translucent with fading effect will appear. It will block touch to other windows under the background. When user close popup, it is simple to disable.
Thank so much!

**Comment by GaoKaiHaHa** [comment]
hi @takaaptech 
This function is considered, in fact, you only need to add a translucent Image to the BG node below the window.
