### ISSUE TITLE
Best Practice for organizing Sprite and UI Background, UI button image ...

### ISSUE THREAD

**Issue by takaaptech** [GaoKaiHaHa/MyUnityFrameWork#25]
Hi @GaoKaiHaHa !
What should you comment on storing image, sprite of a game?
Should we include inside Resources folder and then later in production we make it Streaming Assets (Asset Bundle).
Or should we create Sprites folder inside Assets folder and put those images into this?
Thank so much!

**Comment by GaoKaiHaHa** [comment]
Hi @takaaptech 
My usual management method is that resources that need to be dynamically loaded are placed in the Resources folder. Other resources are placed in the Sprite folder under Assets.

**Comment by takaaptech** [comment]
Hi @GaoKaiHaHa !
Thanks, It is the best practice for me!
