### ISSUE TITLE
Bug in Beginner's guide

### ISSUE THREAD

**Issue by takaaptech** [GaoKaiHaHa/MyUnityFrameWork#26]
Hi @GaoKaiHaHa 
I just follow 2 steps in https://github.com/GaoKaiHaHa/MyUnityFrameWork/wiki/Beginner's-guide

Tools -> 新手引导(Beginner's guide) -> 初始化(initialization)
Tools -> 新手引导(Beginner's guide) -> 创建新手引导预设(Create Beginner's guide Perfab)

But now we have the error when adding RectTransform into the mask and then error when assign value here:

//1

Can't add component 'RectTransform' to mask because such a component is already added to the game object!
UnityEngine.GameObject:AddComponent()
UICreateService:CreateGuideWindow() (at Assets/Script/Core/Editor/UI/UICreateService.cs:330)
GuideSystemEditor:CreateGuideSystemWidnow() (at Assets/Script/Core/Editor/GuideSystem/GuideSystemEditor.cs:53)
///2
NullReferenceException: Object reference not set to an instance of an object
UICreateService.CreateGuideWindow () (at Assets/Script/Core/Editor/UI/UICreateService.cs:331)
GuideSystemEditor.CreateGuideSystemWidnow () (at Assets/Script/Core/Editor/GuideSystem/GuideSystemEditor.cs:53)
![screen shot 2018-04-05 at 1 58 26 pm](https://user-images.githubusercontent.com/6276251/38351484-dad837aa-38d9-11e8-93cd-c19bff7e7178.png)

Thanks!

**Comment by GaoKaiHaHa** [comment]
Hi @takaaptech 
Thanks for the feedback, BUG has been fixed :)
