### ISSUE TITLE
Please add example about Guide System to existing UI example

### ISSUE THREAD

**Issue by takaaptech** [GaoKaiHaHa/MyUnityFrameWork#27]
Hi @GaoKaiHaHa 
The error on Guide system now gone, I follow the wiki to create simple guide system but actually it quite hard for me to start.
Would you please add to GUI example (that have a menu, setting, shop and main game window so far) this tutorial:
- Force User click Shop for the first time (Maybe with Circle highlight)
- Click Close Shop
- Guide user press "START GAME" button

Thank so much for supporting me!

**Comment by GaoKaiHaHa** [comment]
Hi @takaaptech
I submitted a beginners guide Demo by DemoStatus :)

**Comment by takaaptech** [comment]
Hi @GaoKaiHaHa !
That so awesome, so quickly for the Guide System! I now can understand how it works.
Just for note, we need to go to Window / Persistent Data to clear Guide Data if we need it happen again.
 
I have another case need your help, how to implement a step that:
 High light Setting Button but do not need to press that button, only need to "Press anywhere to continue", so it means press anywhere on the screen to go to next sep

Thank so much!

**Comment by GaoKaiHaHa** [comment]
HI @takaaptech 
You can listen for a click event on the mask of GuideWndow. When this click event is triggered, you can directly trigger the click event on the corresponding button. : )

**Comment by takaaptech** [comment]
Hi @GaoKaiHaHa 
I am thinking using script API to implement that. For the click event of the mask , I can do it via GuideWindow.
How can we implement the code in GuideSystem or GuideWindow to change to next step in tutorial flow?

**Comment by takaaptech** [comment]
@GaoKaiHaHa 
Thank so much!
