### ISSUE TITLE
Please support Chain (Sequence) For AnimSystem

### ISSUE THREAD

**Issue by takaaptech** [GaoKaiHaHa/MyUnityFrameWork#29]
Hi @GaoKaiHaHa 
When Anim GUI, I need chain (sequence like DoTween) some AnimData. For now, as I know we only can do this by delay and choose right timing between AnimData.
Please support that feature!

**Comment by GaoKaiHaHa** [comment]
hi @takaaptech 
You can add the next animation you want in Anim's callback function to achieve a similar effect.

like this:
````
AnimSystem.Move(go, new Vector3(), Vector3.one, callBack: (obj) =>
{
       AnimSystem.Scale(go_SelectedObj, Vector3.one, Vector3.zero);
});
````

**Comment by takaaptech** [comment]
I got it, thank so much @GaoKaiHaHa !
