### ISSUE TITLE
Support for multi scene in unity

### ISSUE THREAD

**Issue by takaaptech** [GaoKaiHaHa/MyUnityFrameWork#31]
Hi!
Our GUI manager works great with single unity scene.
For multi-scene is there any difference in architect?
Would you please support code to change between scene and loading scene effect for that?
Thank so much!

**Comment by cacccacc** [comment]
不好意思，我的技术很一般，就是来学习的

**Comment by takaaptech** [comment]
Hi @cacccacc 
Thank so much!
