### ISSUE TITLE
Update wiki for "SDK Manager"

### ISSUE THREAD

**Issue by takaaptech** [GaoKaiHaHa/MyUnityFrameWork#32]
Hi @GaoKaiHaHa !
Please update session "SDK Manager". I want to learn how to use SDK Manager to perform ads show, hide 
Thank so much!

**Comment by GaoKaiHaHa** [comment]
SDK Manager made a big adjustment at the beginning of this year. see my [blog](https://www.kisence.com/2018/03/30/android-sdkfang-an/) to understand how to use.:)

**Comment by takaaptech** [comment]
Hi @GaoKaiHaHa I will try to read it ! Thank so much!
