### ISSUE TITLE
请问UI刷新方案是什么呀

### ISSUE THREAD

**Issue by 603010999** [GaoKaiHaHa/MyUnityFrameWork#35]
例如游戏内数据变动了，需要刷新UI，是怎么从数据那边推送到UI上的啊

**Comment by GaoKaiHaHa** [comment]
UIWindow 中有一个方法，`public void AddEventListener(Enum l_Event)`你可以使用它注册你想要监听的数据改变事件，当数据改变时，可以通过`GlobalEvent.DispatchEvent(Enum type, params object[] args)`进行派发，UIWindow接收到这个事件会自行调用`OnRefresh`方法，这样你就可以利用这个方法刷新界面了

**Comment by 603010999** [comment]
奥。。了解了。。。
谢谢解答~
