### ISSUE TITLE
Server配置

### ISSUE THREAD

**Issue by uncleniner** [GaoKaiHaHa/MyUnityFrameWork#36]
请问server需要配置什么？

**Comment by Cturbo** [comment]
参考 作者 做的帧同步那个 例子 或许有帮助 朋友 你的 项目 没有报丢失配置文件的话 可以分享下吗

**Comment by uncleniner** [comment]
嗯。。。少了很多配置文件没有上传。。

**Comment by GaoKaiHaHa** [comment]
server ？你是说帧同步项目吗？

**Comment by uncleniner** [comment]
对的。。就是帧同步那个例子。。有很多配置文件没有上传。。。

**Comment by uncleniner** [comment]
看了你的博客，受益很大，如果有幸，很想跑一下项目，调试一下过程，万分感激。

**Comment by GaoKaiHaHa** [comment]
帧同步配置文件缺失的话请提交issue在帧同步项目中
