### ISSUE TITLE
请问UI管理器可以支持端游中那种同时叠加多个窗口显示的情况吗？

### ISSUE THREAD

**Issue by Thomas-JZQ** [GaoKaiHaHa/MyUnityFrameWork#42]
端游中经常见到角色、背包、商城、技能等面板是可以同时显示的，只不过有个谁在上层谁在下层的问题，通常激活的窗口处于最顶层，最先打开的窗口在最低层，而且这些窗口还可以拖拽，我就想知道咱们现在这个UI管理器的设计能不能支持这种情况呢？

**Comment by GaoKaiHaHa** [comment]
暂时不支持拖拽与激活窗口功能
