### ISSUE TITLE
Compile error in new commit code

### ISSUE THREAD

**Issue by takaaptech** [GaoKaiHaHa/MyUnityFrameWork#46]
Hi @GaoKaiHaHa 
This code version has some error like:
- Assets/Script/SDK/GoogleLogin.cs(14,26): error CS0115: `GoogleLogin.Login()' is marked as an override but no suitable method found to override

- Assets/Script/UI/ShopWindow/ShopWindow.cs(14,20): error CS1502: The best overloaded method match for `ScrollRectInput.Init(string, int)' has some invalid arguments

- Duplicate class declares: TableConfigFieldInfo

-- And many more
Could you please check and update the code?
Thank so much!

**Comment by GaoKaiHaHa** [comment]
Sorry,Already fixed ：）

**Comment by takaaptech** [comment]
@GaoKaiHaHa It works now!
Thank so much! Happy New Year and best wish for you!

**Comment by GaoKaiHaHa** [comment]
@takaaptech Thank you ：）
