### ISSUE TITLE
打开后编译报错

### ISSUE THREAD

**Issue by zelinDavid** [GaoKaiHaHa/MyUnityFrameWork#48]

**Comment by zelinDavid** [comment]
![image](https://user-images.githubusercontent.com/16894134/55303039-9093f300-5476-11e9-8a27-2096bff0d814.png)
![image](https://user-images.githubusercontent.com/16894134/55303049-97226a80-5476-11e9-89f7-75df532a072c.png)

你好，我在win10 上 用如图所示版本打开 报错，麻烦看下是什么问题

**Comment by jovensun** [comment]
同样错误。然后在Scripting Define Symbols设置了USE_LUA的宏后，又有其它的报错。

**Comment by GaoKaiHaHa** [comment]
已修复
