### ISSUE TITLE
大佬，请问您这套框架支持ProtolBuffer 或者 sproto吗？

### ISSUE THREAD

**Issue by XINCGer** [GaoKaiHaHa/MyUnityFrameWork#49]
RT，在本项目中没有见到类似的DEMO，网络的那块代码有点复杂，不知从何入手，如果项目中有支持的话，希望作者能在百忙之中给与指点，感激不尽！

**Comment by GaoKaiHaHa** [comment]
目前框架里集成了一套我自己实现的ProtolBuffer协议（ProtocolNetworkService），在NetworkManager初始化时`NetworkManager.Init<ProtocolNetworkService, SocketService>(ProtocolType.Tcp);`这样调用即可，如果想要使用自定义的消息类型，继承INetworkInterface并将其在network初始化时将其传入即可。
