### ISSUE TITLE
ResourcesManifest.json 是如何生成的？

### ISSUE THREAD

**Issue by le0zh** [GaoKaiHaHa/MyUnityFrameWork#5]
请问`ResourcesManifest.json`是如何生成的？

**Comment by GaoKaiHaHa** [comment]
这个文件是通过打包设置管理器自动生成，打开打包设置管理器Window->打包设置管理器，点击->自动添加Resource目录下的资源并保存,就可以生成对应文件

**Comment by le0zh** [comment]
感谢回复，找到啦，很好的框架，值得学习！

**Comment by GaoKaiHaHa** [comment]
感谢使用 : )
