### ISSUE TITLE
 unity2018.4.3f报错Multiple precompiled assemblies with the same name CString.dll included for the current platform. Only one assembly with the same name is allowed per platform.

### ISSUE THREAD

**Issue by yicong1406410220** [GaoKaiHaHa/MyUnityFrameWork#54]
PrecompiledAssemblyException: Multiple precompiled assemblies with the same name CString.dll included for the current platform. Only one assembly with the same name is allowed per platform. Assembly path: {0}
UnityEditor.Scripting.ScriptCompilation.EditorBuildRules.CreateTargetAssemblies (IEnumerable`1 customScriptAssemblies, IEnumerable`1 precompiledAssemblies) (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorBuildRules.cs:249)
UnityEditor.Scripting.ScriptCompilation.EditorCompilation.UpdateCustomTargetAssemblies () (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorCompilation.cs:625)
UnityEditor.Scripting.ScriptCompilation.EditorCompilation.SetAllCustomScriptAssemblyJsons (System.String[] paths) (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorCompilation.cs:735)
UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface.SetAllCustomScriptAssemblyJsons (System.String[] allAssemblyJsons) (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorCompilationInterface.cs:217)
第一次打开什么都没改

**Comment by Starscat1618** [comment]
老哥解决了吗，我也遇到这个问题了，求教

**Comment by yicong1406410220** [comment]
> 老哥解决了吗，我也遇到这个问题了，求教

我记得有2个tolua 文件我删掉了一个 可以运行了
