### ISSUE TITLE
打开项目 运行main场景失败 报错

### ISSUE THREAD

**Issue by yicong1406410220** [GaoKaiHaHa/MyUnityFrameWork#55]
报错
System.TypeInitializationException: An exception was thrown by the type initializer for LuaManager ---> System.DllNotFoundException: tolua
![{df124d02-35e6-4f5d-9397-14624b05eb98}](https://user-images.githubusercontent.com/20357196/61940635-6be4fd80-afc8-11e9-9539-f9d4e7795d99.png)
切换到pc平台才报这个错误，其他平台正常。

**Comment by FangyeReady** [comment]
我也遇到这个情况....暂时没有找到原因, 作者能出来吼一嗓子吗?

**Comment by GaoKaiHaHa** [comment]
这个是由于目前不能全自动切换为Lua模式，需要手动调整一下ToLua的导入设置，或者关闭lua也可

**Comment by FangyeReady** [comment]
关闭Lua后确实没有报错了, 感谢,另外想请教一下"手动调整ToLua导入设置"是怎么个手动调整...

**Comment by GaoKaiHaHa** [comment]
就是将 Script/Core/Lua/ToLua/Plugins 下面的 x86 和 x86_64 的两个dll 正确设置一下就好哈，我已提交到git

**Comment by FangyeReady** [comment]
> 就是将 Script/Core/Lua/ToLua/Plugins 下面的 x86 和 x86_64 的两个dll 正确设置一下就好哈，我已提交到git

收到, 感谢!
