### ISSUE TITLE
求一个简单的使用该框架做出的demo

### ISSUE THREAD

**Issue by yangluoqin** [GaoKaiHaHa/MyUnityFrameWork#57]
有人使用这个框架做出过demo么，功能简单的就行，如果可以的话，希望可以提供下

**Comment by GaoKaiHaHa** [comment]
可以看下这个项目https://github.com/GaoKaiHaHa/mySwordMan

**Comment by yangluoqin** [comment]
> 可以看下这个项目https://github.com/GaoKaiHaHa/mySwordMan
好的哈
