### ISSUE TITLE
你好，我每次打开脚本都会提示 没有找到sln的报错请问怎么解决

### ISSUE THREAD

**Issue by FatQuan** [GaoKaiHaHa/MyUnityFrameWork#66]
![image](https://user-images.githubusercontent.com/32729017/160888300-391e4b0e-882f-4620-8de1-0b7621a7a160.png)
我每次打开脚本都会提示 没有找到sln的报错请问怎么解决

**Comment by jonny91** [comment]
您好，你的邮件我已收到。会尽快查阅。
