### ISSUE TITLE
请问配置编辑器和数据编辑器在使用的时候有什么区别呀？

### ISSUE THREAD

**Issue by 603010999** [GaoKaiHaHa/MyUnityFrameWork#8]
我自己的理解是，配置是key,value串，数据更像是表格
但是数据如果需要使用嵌套类型，需要怎么操作呀

还有在配置里看到了可将类序列化保存到配置中，保存之后是可以自动生成类的吗，要怎么生成呢。

**Comment by GaoKaiHaHa** [comment]
数据如果想要嵌套，一般的做法是建立两个表，其中一个表引用另外一个表的ID。

可序列化类到配置中这个是比较早期的功能了，现在你可以通过框架提供的序列化方法把类序列化后，把类保存起来。  

例如
```CSharp
public  void SaveClass(string name,object data)
{
    string configDataJson = Json.Serialize(data);
    string path = PathTool.GetEditorPath("SerializeClass", name, "txt")
    EditorUtil.WriteStringByFile(path , configDataJson);
}

public T GetSaveClass<T>(string name)
{
    string json = ResourceManager.ReadTextFile(name);
    T class =  (T)Json.Deserialize(json)；
    return class
}
```

**Comment by 603010999** [comment]
谢谢回答。。
还想问下，平时大多使用excel或者csv这种可以批量操作的文件
那么策划配置的时候，如果只用数据编辑器，如何高效的配表呢

**Comment by GaoKaiHaHa** [comment]
数据表文件可以直接使用WPS打开并编辑，但要注意WPS的保存格式是ASCII码，如果有中文的话记得切换成utf-8码保存，如果想用excel编辑的话，一种办法是直接把数据文件复制到excel中编辑，再复制回来，还有就是使用转换工具，这个其实我开发了，但是并没有集成到框架中去，是一个独立的工具。

**Comment by 603010999** [comment]
嗯，了解了。
框架挺好用的，谢谢分享
期待wiki的其他部分，好多功能还没看不造怎么用:)

**Comment by GaoKaiHaHa** [comment]
哈哈，谢谢，就是懒得写文档呀。
