### ISSUE TITLE
[UI] - Support function CloseUI without parameter will close last window

### ISSUE THREAD

**Issue by takaaptech** [GaoKaiHaHa/MyUnityFrameWork#9]
Hi!
When using with UI system, I think we should keep a list of the open window in a stack so we can push and pop the latest window.
With that support, we can easily implement default back behavior on Android by call CloseLastOpenedUI(), we can easily close the latest open popup ... without knowing the name of the window
What do you think about that?
Thank so much!

**Comment by GaoKaiHaHa** [comment]
You're right. I'll add this feature later 😄

**Comment by takaaptech** [comment]
Add this as soon as posible please !!!! 💯

**Comment by takaaptech** [comment]
And we can close this when we add feature

**Comment by GaoKaiHaHa** [comment]
hi
I added this feature, please update.
`UIManager.CloseLastUI(uiType)`

**Comment by takaaptech** [comment]
Thank so much @GaoKaiHaHa !
I think put CloseLastUI into OnClickCLose of ShopWindow is the best demo for the usage of that function.

**Comment by GaoKaiHaHa** [comment]
👍
